FROM docker.elastic.co/logstash/logstash:7.5.1

RUN rm /usr/share/logstash/pipeline/logstash.conf
# COPY ./io.conf /usr/share/logstash/pipeline/io.conf
# COPY ./filter.conf /usr/share/logstash/pipeline/filter.conf
